# Generated by Django 3.1.2 on 2022-09-11 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='in_ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_user_ip', models.CharField(max_length=999)),
            ],
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='user_ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.in_ip'),
        ),
    ]
