# Generated by Django 3.1.2 on 2022-09-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220912_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='user_ip',
            field=models.CharField(max_length=999),
        ),
    ]
