# Generated by Django 3.1.2 on 2022-09-11 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220912_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraph',
            name='user_ip',
        ),
        migrations.AddField(
            model_name='paragraph',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.in_ip'),
        ),
    ]
