# Generated by Django 3.1.2 on 2022-09-11 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220912_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph',
            old_name='belongs_to',
            new_name='user_ip',
        ),
    ]
