# Generated by Django 3.1.2 on 2022-09-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220912_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='user_ip',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
