# Generated by Django 3.1.2 on 2022-09-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220912_0153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='in_ip',
        ),
        migrations.AddField(
            model_name='paragraph',
            name='username',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
